// Refreshes src/data/youtube.js from the channel's public RSS feed.
//
// YouTube only exposes a "latest uploads" list through the Data API (needs a
// key) or this feed. The feed sends no CORS header, so the browser can't read
// it directly — we fetch it at build time instead. Netlify runs `npm run build`
// on every push, so the list refreshes on each deploy.
//
// If the fetch fails we keep whatever is already committed rather than
// shipping an empty strip: a stale list beats a broken section.

import { writeFile, access } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const CHANNEL_ID = 'UCjKqqFrMgdWADRmY35A7URw'
const FEED = `https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL_ID}`
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data', 'youtube.js')
const MAX = 12

function decode(s) {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
}

function parse(xml) {
  const entries = xml.split('<entry>').slice(1)
  return entries.slice(0, MAX).map((e) => {
    const pick = (re) => (e.match(re) || [, ''])[1]
    return {
      id: pick(/<yt:videoId>([^<]+)<\/yt:videoId>/),
      title: decode(pick(/<title>([^<]*)<\/title>/)),
      published: pick(/<published>([^T<]+)/),
    }
  }).filter((v) => v.id)
}

const q = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'"

function render(videos) {
  let out = `// Generated by scripts/fetch-youtube.mjs — do not edit by hand.
// Refreshed automatically on every build; see that script for why.
export const channelId = ${q(CHANNEL_ID)}

export const videos = [
`
  for (const v of videos) {
    out += `  { id: ${q(v.id)}, published: ${q(v.published)}, title:\n    ${q(v.title)} },\n`
  }
  out += `]\n`
  return out
}

async function main() {
  let res
  try {
    res = await fetch(FEED, { signal: AbortSignal.timeout(20000) })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
  } catch (err) {
    console.warn(`[fetch-youtube] feed unreachable (${err.message}) — keeping committed list`)
    try {
      await access(OUT)
      return
    } catch {
      console.error('[fetch-youtube] no committed list to fall back to')
      process.exitCode = 1
      return
    }
  }

  const videos = parse(await res.text())
  if (!videos.length) {
    console.warn('[fetch-youtube] feed had no entries — keeping committed list')
    return
  }

  await writeFile(OUT, render(videos), 'utf8')
  console.log(`[fetch-youtube] wrote ${videos.length} videos (latest: ${videos[0].title})`)
}

main()
